### ISSUE TITLE
Revisión del modelo de probabilidades

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/usaid_procesos_interfaz#43]
Revisar ejecución del modelo de probabilidades (01_prediction.R) en el contenedor Linux (Imagen de Docker)

**Comment by Dan3s** [comment]
01_prediccion.R corriendo. Si corre en Windows correrá con los ejecutables .bat y en Linux con .sh

**Comment by stevensotelo** [comment]
El script se encuentra funcionando correctamente tanto en linux como windows. Para linux se reviso en el contenedor de Docker
