### ISSUE TITLE
Revisión del script de generación de escenarios

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/usaid_procesos_interfaz#44]
Revisar ejecución del script que genera los escenarios climáticos  en el contenedor Linux (Imagen de Docker)

**Comment by Dan3s** [comment]
Para 01_prediccion.R se cambiaron las extensiones de los ejecutables dependiendo del SO. También se le dio permisos a los ejecutables en caso de que los pida

**Comment by Dan3s** [comment]
Para 02_remuestreo.R se cambió la ruta de descarga de CHIRP Daily.  Se usó https://data.chc.ucsb.edu/products/CHIRP/daily/

**Comment by Dan3s** [comment]
01_prediccion.R falla pues al descargar los archivos TSM estos solo contienen errores y no datos.
