### ISSUE TITLE
Revisar modelo Oryza

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/usaid_procesos_interfaz#45]
Revisar que está ocurriendo con los scripts del modelo de cultivo

**Comment by Dan3s** [comment]
Se adecuó el llamado al ejecutable dependiendo del SO en el script main_functions.R. Se logró correr el modelo en la Imagen. Ahora se adecuará para que corra en el script main_functions.R.

**Comment by Dan3s** [comment]
Se agregó una condición para que dependiendo del SO ponga la ruta del WTRDIR con los slash adecuados.

**Comment by Dan3s** [comment]
Se logró correr el modelo desde el script en la Imagen de Docker. Se corrió con un escenario para evitar la demora. Al final, arrojó un archivo CSV (queda adjunto).
