### ISSUE TITLE
Revisar modelo DSSAT

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/usaid_procesos_interfaz#46]
Revisar que sucede con el modelo DSSAT

**Comment by Dan3s** [comment]
Se corrigieron los errores de formato del archivo DSSBatch.v47. Se corrigieron los archivos de entrada para que tuvieran el archivo de coordenadas.csv  
Se borraron unos comentarios que provocaban el fallo al correr el siguiente setup. 

El modelo está corriendo.
